name: ContinuousIntegration Debug NuGet

on:
  push:
    branches-ignore:
     - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.100
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Create NuGet Package
      run: dotnet pack -c PackNuGet /p:Version=0.0.0
      working-directory: ./src/