name: ContinuousIntegration Release NuGet

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.100
        source-url: https://nuget.pkg.github.com/sverigesradio/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Create NuGet Package
      run: dotnet pack -c PackNuGet /p:Version=${{ github.event.release.tag_name }} /p:PackageReleaseNotes="See https://github.com/sverigesradio/nuget-ember-plus-provider-lib/releases/tag/${{ github.event.release.tag_name }}"
      working-directory: ./src/

    - name: Upload NuGet Package
      uses: actions/upload-artifact@v3
      with:
        name: SR.EmberPlusProviderLib.NetStandard
        path: ./src/Nuget.EmberPlusProviderLib.NetStandard/bin/PackNuGet/SR.EmberPlusProviderLib.NetStandard.${{ github.event.release.tag_name }}.nupkg

    - name: Publish NuGet Package
      run: dotnet nuget push ./src/Nuget.EmberPlusProviderLib.NetStandard/bin/PackNuGet/SR.EmberPlusProviderLib.NetStandard.${{ github.event.release.tag_name }}.nupkg --skip-duplicate --no-symbols -k ${{secrets.GITHUB_TOKEN}} -s https://nuget.pkg.github.com/sverigesradio/index.json
